"""
Channel-specific response formatters.
"""

from enum import Enum


class Channel(str, Enum):
    EMAIL = "email"
    WHATSAPP = "whatsapp"
    WEB_FORM = "web_form"


async def format_for_channel(response: str, channel: Channel, ticket_id: str = None) -> str:
    """
    Format response appropriately for the channel.

    Args:
        response: The agent's response text
        channel: The target channel
        ticket_id: Optional ticket reference

    Returns:
        Formatted response string
    """

    if channel == Channel.EMAIL:
        return format_email_response(response, ticket_id)
    elif channel == Channel.WHATSAPP:
        return format_whatsapp_response(response)
    else:  # web_form
        return format_web_form_response(response, ticket_id)


def format_email_response(response: str, ticket_id: str = None) -> str:
    """Format response for email channel."""
    ticket_ref = f"\n\nTicket Reference: {ticket_id}" if ticket_id else ""

    return f"""Dear Customer,

Thank you for reaching out to TechCorp Support.

{response}

If you have any further questions, please don't hesitate to reply to this email.

Best regards,
TechCorp AI Support Team{ticket_ref}
---
This response was generated by our AI assistant. For complex issues, you can request human support."""


def format_whatsapp_response(response: str, max_length: int = 300) -> str:
    """Format response for WhatsApp channel."""
    # Keep it short for WhatsApp
    if len(response) > max_length:
        response = response[:max_length - 50] + "..."

    return f"{response}\n\n📱 Reply for more help or type 'human' for live support."


def format_web_form_response(response: str, ticket_id: str = None) -> str:
    """Format response for web form channel."""
    ticket_ref = f"\n\nTicket ID: {ticket_id}" if ticket_id else ""

    return f"""{response}{ticket_ref}

---
Need more help? Reply to this message or visit our support portal at https://techcorp.com/support"""


def truncate_response(response: str, max_length: int) -> str:
    """
    Truncate response to max length while preserving sentence boundaries.

    Args:
        response: The response text
        max_length: Maximum character length

    Returns:
        Truncated response
    """
    if len(response) <= max_length:
        return response

    # Try to break at sentence boundary
    truncated = response[:max_length - 3]
    last_period = truncated.rfind('. ')

    if last_period > max_length * 0.7:  # If we can keep at least 70% of content
        return truncated[:last_period + 1]

    # Otherwise, break at word boundary
    last_space = truncated.rfind(' ')
    if last_space > 0:
        return truncated[:last_space] + "..."

    return truncated + "..."


def extract_greeting(channel: Channel) -> str:
    """Get appropriate greeting for channel."""
    if channel == Channel.EMAIL:
        return "Dear Customer,"
    elif channel == Channel.WHATSAPP:
        return "Hi!"
    else:
        return "Hello!"


def extract_closing(channel: Channel) -> str:
    """Get appropriate closing for channel."""
    if channel == Channel.EMAIL:
        return "Best regards,\nTechCorp Support Team"
    elif channel == Channel.WHATSAPP:
        return "Thanks! 😊"
    else:
        return "Best regards,\nTechCorp Support"
